'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Plantilla

  '''<summary>
  '''head control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

  '''<summary>
  '''form1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''udp_base control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents udp_base As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''cph_botones control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cph_botones As Global.System.Web.UI.WebControls.ContentPlaceHolder

  '''<summary>
  '''mainNav control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents mainNav As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''lkb_cerrarsesion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_cerrarsesion As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''div_mensajes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents div_mensajes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''cph_contenido control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cph_contenido As Global.System.Web.UI.WebControls.ContentPlaceHolder

  '''<summary>
  '''ScriptManager1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
End Class
