'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProfesionesView

  '''<summary>
  '''lkb_buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_buscar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_agregar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_agregar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_guardar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_guardar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_eliminar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_eliminar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_salir control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_salir As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''pnl_form control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_form As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lbl_nombres control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_nombres As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txt_nombres control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_nombres As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''pnl_list control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_list As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''pnl_buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_buscar As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''ddl_buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddl_buscar As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txt_bucar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_bucar As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btn_filtrar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btn_filtrar As Global.System.Web.UI.HtmlControls.HtmlButton

  '''<summary>
  '''grd_Profesiones control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents grd_Profesiones As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''sds_Profesiones control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents sds_Profesiones As Global.System.Web.UI.WebControls.SqlDataSource

  '''<summary>
  '''hdf_id control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdf_id As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As Adya.CV.Web._Plantilla
    Get
      Return CType(MyBase.Master, Adya.CV.Web._Plantilla)
    End Get
  End Property
End Class
