'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UsuariosView

  '''<summary>
  '''lkb_buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_buscar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_agregar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_agregar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_guardar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_guardar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_eliminar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_eliminar As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lkb_salir control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lkb_salir As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''pnl_form control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_form As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lbl_nombres control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_nombres As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txt_nombres control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_nombres As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lbl_apellidos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_apellidos As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txt_apellidos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_apellidos As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lbl_usuario control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_usuario As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txt_usuario control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_usuario As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lbl_admin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_admin As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''rbl_administrador control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rbl_administrador As Global.System.Web.UI.WebControls.RadioButtonList

  '''<summary>
  '''lbl_clave control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_clave As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txt_clave control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_clave As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lbl_confirmaclave control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl_confirmaclave As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txt_confirmaclave control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_confirmaclave As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''pnl_menus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_menus As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''li_hojadevidas control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_hojadevidas As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_inventarios control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_inventarios As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_usuarios control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_usuarios As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_actividades control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_actividades As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_ingresos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_ingresos As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_areas control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_areas As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_empleados control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_empleados As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_cargos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_cargos As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_proveedores control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_proveedores As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_ciudades control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_ciudades As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_tallas control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_tallas As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_nacionalidades control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_nacionalidades As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''li_profesiones control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents li_profesiones As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''pnl_list control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_list As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''pnl_buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnl_buscar As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''ddl_buscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddl_buscar As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txt_bucar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt_bucar As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btn_filtrar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btn_filtrar As Global.System.Web.UI.HtmlControls.HtmlButton

  '''<summary>
  '''grd_usuarios control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents grd_usuarios As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''sds_usuarios control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents sds_usuarios As Global.System.Web.UI.WebControls.SqlDataSource

  '''<summary>
  '''hdf_id control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdf_id As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As Adya.CV.Web._Plantilla
    Get
      Return CType(MyBase.Master, Adya.CV.Web._Plantilla)
    End Get
  End Property
End Class
