'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AreasxHojadeVida
    Public Property AreaxHojadeVidaId As Integer
    Public Property HojadeVidaFk As Integer
    Public Property AreaFk As Integer
    Public Property Valor As Boolean

    Public Overridable Property Areas As Areas
    Public Overridable Property HojadeVidas As HojadeVidas

End Class
