'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cargos
    Public Property CargoId As Integer
    Public Property Nombre As String
    Public Property Codigo As String

    Public Overridable Property ExperienciaLaborales As ICollection(Of ExperienciaLaborales) = New HashSet(Of ExperienciaLaborales)
    Public Overridable Property ExperienciaLaborales1 As ICollection(Of ExperienciaLaborales) = New HashSet(Of ExperienciaLaborales)
    Public Overridable Property InformacionFamiliares As ICollection(Of InformacionFamiliares) = New HashSet(Of InformacionFamiliares)
    Public Overridable Property HojadeVidas As ICollection(Of HojadeVidas) = New HashSet(Of HojadeVidas)

End Class
