'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ciudades
    Public Property CiudadId As Integer
    Public Property Nombre As String

    Public Overridable Property Educaciones As ICollection(Of Educaciones) = New HashSet(Of Educaciones)
    Public Overridable Property InformacionFamiliares As ICollection(Of InformacionFamiliares) = New HashSet(Of InformacionFamiliares)
    Public Overridable Property HojadeVidas As ICollection(Of HojadeVidas) = New HashSet(Of HojadeVidas)
    Public Overridable Property HojadeVidas1 As ICollection(Of HojadeVidas) = New HashSet(Of HojadeVidas)
    Public Overridable Property HojadeVidas2 As ICollection(Of HojadeVidas) = New HashSet(Of HojadeVidas)

End Class
