'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Conocimientos
    Public Property ConocimientoId As Integer
    Public Property HojadeVidaFk As Integer
    Public Property Tipo As Integer
    Public Property Descripcion As String
    Public Property SistemasNivel As String
    Public Property InglesLectura As String
    Public Property InglesEscucha As String
    Public Property InglesHablado As String

    Public Overridable Property HojadeVidas As HojadeVidas

End Class
