'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleIngresos
    Public Property DetalleIngresoId As Integer
    Public Property IngresoFk As Integer
    Public Property ProductoFk As Integer
    Public Property TallaFk As Integer
    Public Property Cantidad As Integer

    Public Overridable Property Ingresos As Ingresos
    Public Overridable Property Productos As Productos
    Public Overridable Property Tallas As Tallas

End Class
