'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Educaciones
    Public Property EducacionId As Integer
    Public Property HojadeVidaFk As Integer
    Public Property Estudio As Integer
    Public Property AnoFin As Integer
    Public Property Titulo As String
    Public Property Institucion As String
    Public Property CiudadFk As Integer
    Public Property TiempoCursado As Integer
    Public Property TipoTiempo As Integer

    Public Overridable Property Ciudades As Ciudades
    Public Overridable Property HojadeVidas As HojadeVidas

End Class
