'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property EmpleadoId As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property NumeroIdentificacion As String
    Public Property FechaIngreso As Date

    Public Overridable Property ProductosxEmpleados As ICollection(Of ProductosxEmpleados) = New HashSet(Of ProductosxEmpleados)
    Public Overridable Property ProductosxEmpleados1 As ICollection(Of ProductosxEmpleados) = New HashSet(Of ProductosxEmpleados)

End Class
