'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ExperienciaLaborales
    Public Property ExperienciaLaboralId As Integer
    Public Property HojadeVidaFk As Integer
    Public Property Empresa As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property JefeCargoFk As Integer
    Public Property JefeInmediato As String
    Public Property Ingreso As Date
    Public Property Retiro As Date
    Public Property TiempoServicio As String
    Public Property SueldoInicial As Decimal
    Public Property SueldoFinal As Decimal
    Public Property CargoFk As Integer
    Public Property Funciones As String
    Public Property Logros As String
    Public Property TipoContrato As Integer
    Public Property HorarioTrabajo As Integer
    Public Property Jornada As Integer
    Public Property MotivoRetiro As String

    Public Overridable Property Cargos As Cargos
    Public Overridable Property Cargos1 As Cargos
    Public Overridable Property HojadeVidas As HojadeVidas

End Class
