'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HojadeVidas
    Public Property HojadeVidaId As Integer
    Public Property Fecha As Date
    Public Property CargoFk As Integer
    Public Property Estado As Integer
    Public Property Apellidos As String
    Public Property Nombres As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Celular As String
    Public Property Correo As String
    Public Property CiudadFk As Integer
    Public Property NacionalidadFk As Integer
    Public Property ProfesionFk As Integer
    Public Property EstadoCivil As Integer
    Public Property AnosExperiencia As Integer
    Public Property MesesExperiencia As Integer
    Public Property TipoDocumento As Integer
    Public Property NumeroIdentificacion As String
    Public Property ExpedicionCiudadFk As Integer
    Public Property LibretaMilitar As String
    Public Property Distrito As Integer
    Public Property Clase As Integer
    Public Property TarjetaProfesional As String
    Public Property Vehiculo As Boolean
    Public Property LicenciaConduccion As String
    Public Property Categoria As String
    Public Property TrabajaActualmente As Boolean
    Public Property Empresa As String
    Public Property Independiente As Nullable(Of Boolean)
    Public Property TipoContrato As Nullable(Of Integer)
    Public Property TrabajoAntesEstaEmpresa As Boolean
    Public Property SolicitoAntesEstaEmpresa As Boolean
    Public Property SolicitoAntesFechaEstaEmpresa As Nullable(Of Boolean)
    Public Property Recomendado As Boolean
    Public Property Nombre As String
    Public Property Dependencia As String
    Public Property ConocioVacante As Integer
    Public Property ConocioOtro As String
    Public Property VividoCiudadFk As Integer
    Public Property TrabajarOtraCiudad As Boolean
    Public Property ViveCasa As Integer
    Public Property NombreArrendador As String
    Public Property TelefonoArreandador As String
    Public Property AnosResidencia As Integer
    Public Property MesesResidencia As Integer
    Public Property IngresoAdicional As Boolean
    Public Property DescripcionIngresoAdicional As String
    Public Property ValorIngresoAdicional As Nullable(Of Decimal)
    Public Property ValorObligacionMensual As Decimal
    Public Property ConceptoObligacionMensual As String
    Public Property AspiracionSalarial As Decimal
    Public Property PrincipalesAficiones As String
    Public Property Deportes As String
    Public Property Menciones As Boolean
    Public Property DescripcionMenciones As String
    Public Property Asociacion As Boolean
    Public Property DescripcionAsociacion As String
    Public Property Objetivo As String
    Public Property NumeroPersonasDependen As Integer

    Public Overridable Property ActividadesxHojadeVida As ICollection(Of ActividadesxHojadeVida) = New HashSet(Of ActividadesxHojadeVida)
    Public Overridable Property AreasxHojadeVida As ICollection(Of AreasxHojadeVida) = New HashSet(Of AreasxHojadeVida)
    Public Overridable Property Cargos As Cargos
    Public Overridable Property Ciudades As Ciudades
    Public Overridable Property Ciudades1 As Ciudades
    Public Overridable Property Ciudades2 As Ciudades
    Public Overridable Property Conocimientos As ICollection(Of Conocimientos) = New HashSet(Of Conocimientos)
    Public Overridable Property Educaciones As ICollection(Of Educaciones) = New HashSet(Of Educaciones)
    Public Overridable Property EstudioActuales As ICollection(Of EstudioActuales) = New HashSet(Of EstudioActuales)
    Public Overridable Property ExperienciaLaborales As ICollection(Of ExperienciaLaborales) = New HashSet(Of ExperienciaLaborales)
    Public Overridable Property Nacionalidades As Nacionalidades
    Public Overridable Property Profesiones As Profesiones
    Public Overridable Property InformacionFamiliares As ICollection(Of InformacionFamiliares) = New HashSet(Of InformacionFamiliares)
    Public Overridable Property ReferenciaPersonales As ICollection(Of ReferenciaPersonales) = New HashSet(Of ReferenciaPersonales)
    Public Overridable Property SeguridadesSociales As ICollection(Of SeguridadesSociales) = New HashSet(Of SeguridadesSociales)

End Class
