'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InformacionFamiliares
    Public Property InformacionFamiliarId As Integer
    Public Property HojadeVidaFk As Integer
    Public Property Nombre As String
    Public Property ProfesionFk As Integer
    Public Property Empresa As String
    Public Property CargoFk As Nullable(Of Integer)
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property CiudadFk As Integer
    Public Property Edad As Integer
    Public Property Parentesco As Integer
    Public Property OtroParentesco As String

    Public Overridable Property Cargos As Cargos
    Public Overridable Property Ciudades As Ciudades
    Public Overridable Property HojadeVidas As HojadeVidas

End Class
