'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ingresos
    Public Property IngresoId As Integer
    Public Property FechaIngreso As Date
    Public Property ProveedorFk As Integer

    Public Overridable Property DetalleIngresos As ICollection(Of DetalleIngresos) = New HashSet(Of DetalleIngresos)
    Public Overridable Property Proveedores As Proveedores

End Class
