'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductosxEmpleados
    Public Property ProductoxEmpleadoId As Integer
    Public Property EmpleadoFk As Integer
    Public Property ProductoxTallaFk As Integer
    Public Property Cantidad As Integer
    Public Property Fecha As Date
    Public Property Tipo As Integer
    Public Property TipoDevolucion As Nullable(Of Integer)

    Public Overridable Property Empleados As Empleados
    Public Overridable Property Empleados1 As Empleados
    Public Overridable Property ProductosxTallas As ProductosxTallas

End Class
