'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Profesiones
    Public Property ProfesionId As Integer
    Public Property Nombre As String

    Public Overridable Property HojadeVidas As ICollection(Of HojadeVidas) = New HashSet(Of HojadeVidas)

End Class
