'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property ProveedorId As Integer
    Public Property NumeroIdentificacion As String
    Public Property Nombre As String
    Public Property Telefono As String
    Public Property Direccion As String

    Public Overridable Property Ingresos As ICollection(Of Ingresos) = New HashSet(Of Ingresos)

End Class
