'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReferenciaPersonales
    Public Property ReferenciaPersonalId As Integer
    Public Property HojadeVidaFk As Integer
    Public Property Familiar As Boolean
    Public Property Nombre As String
    Public Property CargoFk As Integer
    Public Property Direccion As String
    Public Property Telefono As String

    Public Overridable Property HojadeVidas As HojadeVidas

End Class
